#!/usr/bin/env bash
#

for file in *
do
    case "$file" in
        -*)
            continue
            ;;
        *-*)
            echo "${file#*-}"
            ;;
        *)
            if [ "$file" != "8-for_ls" ]; then
                echo "$file"
            fi
            ;;
    esac
done

echo "for_ls"

