#!/usr/bin/env bash
#
if [ ! -e school ]; then
    echo "school doesn’t exist"
else
    if [ -f school ]; then
        if [ -s school ]; then
            echo "File exist and is a regular file"
        else
            echo "school exists but empty"
        fi
    else
        echo "school exists but it’s a directory"
    fi
fi

