#!/usr/bin/env bash
#
if [ ! -e school ]; then
    echo "school file does not exist"
else
    echo "school file exists"

    if [ -f school ]; then
        echo "school is a regular file"

        if [ -s school ]; then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
    else
        echo "school file is not empty"
    fi
fi

